apiVersion: skaffold/v2beta10
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: mroobert/auth-service
      context: auth
      docker: 
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'auth/src/**/*.ts'
            dest: .
    - image: mroobert/client-app-ticketing
      context: client
      docker: 
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'client/src/**/*.ts'
            dest: .
    - image: mroobert/tickets-service
      context: tickets
      docker: 
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'tickets/src/**/*.ts'
            dest: .
